export const iconClassMap = {
  'bold': 'material-symbols-outlined format-bold',
  'italic': 'material-symbols-outlined format-italic',
  'strikethrough': 'material-symbols-outlined format-strikethrough',
  'heading': 'fa fa-header fa-heading',
  'heading-smaller': 'material-symbols-outlined text-decrease',
  'heading-bigger': 'material-symbols-outlined text-increase',
  'heading-1': 'material-symbols-outlined format-h-1',
  'heading-2': 'material-symbols-outlined format-h-2',
  'heading-3': 'material-symbols-outlined format-h-3',
  'code': 'material-symbols-outlined code',
  'quote': 'material-symbols-outlined format-quote',
  'ordered-list': 'material-symbols-outlined format-list-bulleted',
  'unordered-list': 'material-symbols-outlined format-list-numbered',
  'clean-block': 'fa fa-eraser',
  'link': 'fa fa-link',
  'image': 'fa fa-image',
  'upload-image': 'fa fa-image',
  'table': 'fa fa-table',
  'horizontal-rule': 'fa fa-minus',
  'preview': 'fa fa-eye',
  'side-by-side': 'fa fa-columns',
  'fullscreen': 'fa fa-arrows-alt',
  'guide': 'fa fa-question-circle',
  'undo': 'fa fa-undo',
  'redo': 'fa fa-repeat fa-redo',
};
