export const iconClassMap = {
  'bold': 'material-symbols-outlined format-bold',
  'italic': 'material-symbols-outlined format-italic',
  'strikethrough': 'material-symbols-outlined format-strikethrough',
  'heading': 'fa fa-header fa-heading',
  'heading-smaller': 'material-symbols-outlined text-decrease',
  'heading-bigger': 'material-symbols-outlined text-increase',
  'heading-1': 'material-symbols-outlined format-h-1',
  'heading-2': 'material-symbols-outlined format-h-2',
  'heading-3': 'material-symbols-outlined format-h-3',
  'code': 'material-symbols-outlined code',
  'quote': 'material-symbols-outlined format-quote',
  'ordered-list': 'material-symbols-outlined format-list-bulleted',
  'unordered-list': 'material-symbols-outlined format-list-numbered',
  'preview': 'material-symbols-outlined visibility',
  'link': 'material-symbols-outlined link',
  'side-by-side': 'material-symbols-outlined vertical-split',
  'fullscreen': 'material-symbols-outlined fullscreen',
  'horizontal-rule': 'material-symbols-outlined horizontal-rule',
  'guide': 'material-symbols-outlined help',
  'undo': 'material-symbols-outlined undo',
  'redo': 'material-symbols-outlined  redo',
};
